- id: doi:10.1016/j.ccell.2023.10.008
  type: paper
  description: Testing.
  image: https://www.cell.com/cms/attachment/34df0d4d-b3c4-459a-8a9e-b390a7a7e450/fx1.jpg
  buttons:
    - type: source
      text: Manuscript Source
      link: https://github.com/MarraLab/Longitudinal_pAML_paper
  tags:
    - pAML
    - scRNA-seq
    - scATAC-seq